# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-24 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('leave_from', models.DateField(blank=True, null=True)),
                ('leave_to', models.DateField(blank=True, null=True)),
                ('no_of_days', models.IntegerField()),
                ('leave_reason', models.TextField(blank=True, max_length=200, null=True)),
                ('approval_status', models.CharField(max_length=200)),
                ('reject_reason', models.TextField(blank=True, max_length=200, null=True)),
                ('lop', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='approved_by')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'leave_requests',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leave', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('balance_leave', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'leave_statuses',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=200)),
                ('no_of_days', models.IntegerField()),
                ('current_year', models.IntegerField()),
                ('leave_status', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'leave_types',
            },
        ),
        migrations.AddField(
            model_name='status',
            name='cur_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_status_current_year', to='leave.Type', verbose_name='current_year'),
        ),
        migrations.AddField(
            model_name='status',
            name='empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_status_empid', to='leave.Request', verbose_name='empid'),
        ),
        migrations.AddField(
            model_name='status',
            name='leave_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_status_leave_id', to='leave.Type', verbose_name='leave_id'),
        ),
        migrations.AddField(
            model_name='request',
            name='leave_nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.Type'),
        ),
    ]
