# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-25 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20180925_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='leave_nature',
            field=models.ForeignKey(blank=True, db_column='leave_nature', null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.Type'),
        ),
    ]
