# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-25 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20180925_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='empid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
