# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-25 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_auto_20180925_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='id',
        ),
        migrations.AlterField(
            model_name='status',
            name='empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='leave_status_empid', serialize=False, to='leave.Request', verbose_name='empid'),
        ),
    ]
