# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-25 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_auto_20180925_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name_plural': 'Leave Request '},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Leave Status'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': 'Leave Type'},
        ),
        migrations.AlterField(
            model_name='status',
            name='empid',
            field=models.ForeignKey(db_column='empid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='leave_status_empid', serialize=False, to='leave.Request', verbose_name='empid'),
        ),
    ]
