# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-25 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_auto_20180925_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='cur_year',
            field=models.ForeignKey(db_column='cur_year', on_delete=django.db.models.deletion.CASCADE, related_name='leave_status_current_year', to='leave.Type', verbose_name='current_year'),
        ),
    ]
