# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-26 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0015_auto_20180926_1102'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='type',
            table='leave_types',
        ),
    ]
