# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-27 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0016_auto_20180926_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('leave_from', models.DateField(blank=True, null=True)),
                ('leave_to', models.DateField(blank=True, null=True)),
                ('no_of_days', models.IntegerField()),
                ('leave_reason', models.TextField(blank=True, max_length=200, null=True)),
                ('approval_status', models.CharField(max_length=200)),
                ('reject_reason', models.TextField(blank=True, max_length=200, null=True)),
                ('lop', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('approved_by', models.ForeignKey(db_column='approved_by', on_delete=django.db.models.deletion.CASCADE, related_name='leave_leaverequest_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='approved_by')),
                ('empid', models.ForeignKey(db_column='empid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_leaverequest_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('leave_nature', models.ForeignKey(blank=True, db_column='leave_nature', null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.Type')),
            ],
            options={
                'db_table': 'leave_requests',
                'verbose_name_plural': 'Leave Request ',
            },
        ),
        migrations.RemoveField(
            model_name='request',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='request',
            name='empid',
        ),
        migrations.RemoveField(
            model_name='request',
            name='leave_nature',
        ),
        migrations.AlterField(
            model_name='status',
            name='empid',
            field=models.ForeignKey(db_column='empid', on_delete=django.db.models.deletion.CASCADE, related_name='leave_status_empid', to='leave.LeaveRequest', verbose_name='empid'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
