# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-27 12:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0017_auto_20180927_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_leaverequest_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='approved_by'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='empid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_leaverequest_empid', to=settings.AUTH_USER_MODEL, verbose_name='empid'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_nature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_leaverequest_leave_nature', to='leave.Type', verbose_name='leave_nature'),
        ),
        migrations.AlterField(
            model_name='status',
            name='cur_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='empid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='status',
            name='leave_id',
            field=models.IntegerField(),
        ),
    ]
