# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-27 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0018_auto_20180927_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(db_column='approved_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_leaverequest_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='approved_by'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='empid',
            field=models.ForeignKey(db_column='empid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_leaverequest_empid', to=settings.AUTH_USER_MODEL, verbose_name='empid'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_nature',
            field=models.ForeignKey(db_column='leave_nature', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_leaverequest_leave_nature', to='leave.Type', verbose_name='leave_nature'),
        ),
    ]
