# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-27 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0019_auto_20180927_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLeaveRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('leave_reason', models.TextField(blank=True, max_length=200, null=True)),
                ('no_of_hours', models.IntegerField()),
                ('approval_status', models.CharField(max_length=200)),
                ('reject_reason', models.TextField(blank=True, max_length=200, null=True)),
                ('approved_by', models.ForeignKey(db_column='approved_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_shortleaverequest_manager', to=settings.AUTH_USER_MODEL, verbose_name='manager')),
                ('empid', models.ForeignKey(db_column='empid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_shortleaverequest_employee', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
            options={
                'db_table': 'shortleave_requests',
                'verbose_name_plural': 'Short Leave Request ',
            },
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='lop',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
