# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-27 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0020_auto_20180927_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortleaverequest',
            name='no_of_hours',
            field=models.IntegerField(default=1),
        ),
    ]
