# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0021_auto_20180927_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='approval_status',
            field=models.CharField(default='Not Yet Approved', max_length=200),
        ),
    ]
