# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-01 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0023_auto_20181001_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='leave_id',
            field=models.BooleanField(),
        ),
    ]
