# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-01 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0024_auto_20181001_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='leave_id',
            field=models.IntegerField(),
        ),
    ]
