# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-24 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0002_auto_20180924_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestt',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='requestt',
            name='empid',
        ),
        migrations.RemoveField(
            model_name='requestt',
            name='leave_nature',
        ),
        migrations.RemoveField(
            model_name='statuss',
            name='cur_year',
        ),
        migrations.RemoveField(
            model_name='statuss',
            name='empid',
        ),
        migrations.RemoveField(
            model_name='statuss',
            name='leave_id',
        ),
        migrations.DeleteModel(
            name='Requestt',
        ),
        migrations.DeleteModel(
            name='Statuss',
        ),
        migrations.DeleteModel(
            name='Typee',
        ),
    ]
