# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymail', '0002_auto_20170607_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mail_id',
            field=models.EmailField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='recognition',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
