# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymail', '0004_auto_20170607_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mail_id',
            field=models.EmailField(max_length=300),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='recognition',
            field=models.CharField(max_length=255),
        ),
    ]
