# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymail', '0005_auto_20170613_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='recognition',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='create_date',
        ),
    ]
