# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-15 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('milestone', '0001_initial'),
        ('projects', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('business_unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmcReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Due_date', models.DateField()),
                ('AMC_end_date', models.DateField()),
                ('notification', models.DateField()),
                ('remarks', models.TextField(max_length=50)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(max_length=20, null=True)),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customet_name', to='business_unit.BusinessUnit', verbose_name='Customer')),
                ('escalation_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalation_role', to='auth.Group', verbose_name='Escalation role')),
                ('milestone_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone_name', to='milestone.Milestone', verbose_name='Milestone')),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution_name', to='projects.Project', verbose_name='Project')),
                ('role', models.ManyToManyField(blank=True, null=True, to='auth.Group', verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_period', models.CharField(max_length=30, verbose_name='Service period')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=False, max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.AddField(
            model_name='amcreport',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amc.Status', verbose_name='Status'),
        ),
    ]
