# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymail', '0003_auto_20170607_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='create_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
